version: 2
updates:
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: "/omadata-oauth2-sample/server"
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: "/omadata-oauth2-sample/client"
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: "/valpas/web"
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: "/smoketests"
    schedule:
      interval: daily
