version: 2
updates:
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: daily
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: "/omadata-oauth2-sample/server"
    schedule:
      interval: daily
    open-pull-requests-limit: 0

  - package-ecosystem: npm
    directory: "/omadata-oauth2-sample/client"
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    
  - package-ecosystem: npm
    directory: "/valpas-web"
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    
  - package-ecosystem: npm
    directory: "/smoketests"
    schedule:
      interval: daily
    open-pull-requests-limit: 0
